### ISSUE TITLE
Migration can not be rolled back

### ISSUE THREAD

**Issue by mebibou** [CultivateLabs/storytime#202]
The 49 so far migrations can not be rollbacked, I keep getting errors on many migrations:
- 20160627055749_remove_storytime_role_id_from_users.storytime.rb
- 20160627055737_remove_homepage_path_from_storytime_sites.storytime.rb
- 20160627055731_remove_root_page_content_from_storytime_sites.storytime.rb
- ...

Please make sure that every migration can be rolled back

**Comment by bcroesch** [comment]
If you're interested in opening a pull for this, we're happy to review & merge.
