### ISSUE TITLE
Fonts no longer available by links to AWS

### ISSUE THREAD

**Issue by Loriowar** [CultivateLabs/storytime#217]
All fonts defined in `app/assets/stylesheets/storytime/icons.scss` no longer available for download (http 403 status). May you provide a name of it and/or alternative place to fetch it?

**Comment by bcroesch** [comment]
@Loriowar - I don't have time currently to troubleshoot, but if you'd like to open a PR, I'm happy to take a look & merge.

**Comment by Loriowar** [comment]
@bcroesch not a problem to create a PR with fix, problem is to find source fonts from https://fontastic.s3.amazonaws.com/ous3EcA2XoT3aZKL2pCQWB/fonts/1423165812.eot and similar links from `icons.scss`. I have no idea where I can find this data.

**Comment by Loriowar** [comment]
Fixed in #218
