### ISSUE TITLE
wrong number of arguments (3 for 0..1) for url_for_with_storytime(options = {}) method.

### ISSUE THREAD

**Issue by MatUrbanski** [CultivateLabs/storytime#49]
I was trying to test storytime gem on blank Ruby on Rails 4.2.0.beta2 app. I've added User model backed with Devise and install storytime according to instruction. When I launch my app and visit localhost:300 I have the following error:

ArgumentError (wrong number of arguments (3 for 0..1)):
  storytime (1.0.1) config/initializers/url_for_patch.rb:5:in `url_for_with_storytime'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:275:in`call'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:218:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:314:in`block (2 levels) in define_url_helper'
  storytime (1.0.1) app/controllers/storytime/application_controller.rb:23:in `ensure_site'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:424:in`block in make_lambda'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:142:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:142:in`block in halting_and_conditional'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:231:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:231:in`block in halting'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:231:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:231:in`block in halting'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:166:in`block in halting'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:166:in`block in halting'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:231:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:231:in`block in halting'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:166:in`block in halting'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:87:in `call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:87:in`run_callbacks'
  actionpack (4.2.0.beta2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0.beta2) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (4.2.0.beta2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0.beta2) lib/active_support/notifications.rb:164:in`block in instrument'
  activesupport (4.2.0.beta2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0.beta2) lib/active_support/notifications.rb:164:in`instrument'
  actionpack (4.2.0.beta2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0.beta2) lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
  activerecord (4.2.0.beta2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0.beta2) lib/abstract_controller/base.rb:137:in`process'
  actionview (4.2.0.beta2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0.beta2) lib/action_controller/metal.rb:195:in`dispatch'
  actionpack (4.2.0.beta2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0.beta2) lib/action_controller/metal.rb:236:in`block in action'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:72:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:72:in`dispatch'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:41:in `serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/mapper.rb:48:in`serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/journey/router.rb:30:in`each'
  actionpack (4.2.0.beta2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:750:in`call'
  railties (4.2.0.beta2) lib/rails/engine.rb:514:in `call'
  railties (4.2.0.beta2) lib/rails/railtie.rb:194:in`public_send'
  railties (4.2.0.beta2) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/mapper.rb:50:in`serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/journey/router.rb:30:in`each'
  actionpack (4.2.0.beta2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0.beta2) lib/action_dispatch/routing/route_set.rb:750:in`call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in`catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0.beta) lib/rack/etag.rb:23:in`call'
  rack (1.6.0.beta) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0.beta) lib/rack/head.rb:13:in`call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/flash.rb:257:in`call'
  rack (1.6.0.beta) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0.beta) lib/rack/session/abstract/id.rb:220:in`call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/cookies.rb:558:in `call'
  activerecord (4.2.0.beta2) lib/active_record/query_cache.rb:36:in`call'
  activerecord (4.2.0.beta2) lib/active_record/connection_adapters/abstract/connection_pool.rb:645:in `call'
  activerecord (4.2.0.beta2) lib/active_record/migration.rb:378:in`call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0.beta2) lib/active_support/callbacks.rb:83:in`run_callbacks'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/reloader.rb:73:in`call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  web-console (2.0.0.beta4) lib/action_dispatch/debug_exceptions.rb:18:in`middleware_call'
  web-console (2.0.0.beta4) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
  railties (4.2.0.beta2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0.beta2) lib/rails/rack/logger.rb:20:in`block in call'
  activesupport (4.2.0.beta2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0.beta2) lib/active_support/tagged_logging.rb:26:in`tagged'
  activesupport (4.2.0.beta2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0.beta2) lib/rails/rack/logger.rb:20:in`call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0.beta) lib/rack/methodoverride.rb:22:in`call'
  rack (1.6.0.beta) lib/rack/runtime.rb:17:in `call'
  activesupport (4.2.0.beta2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
  rack (1.6.0.beta) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0.beta2) lib/action_dispatch/middleware/static.rb:103:in`call'
  rack (1.6.0.beta) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0.beta2) lib/rails/engine.rb:514:in`call'
  railties (4.2.0.beta2) lib/rails/application.rb:161:in `call'
  rack (1.6.0.beta) lib/rack/tempfile_reaper.rb:15:in`call'
  rack (1.6.0.beta) lib/rack/lint.rb:49:in `_call'
  rack (1.6.0.beta) lib/rack/lint.rb:37:in`call'
  rack (1.6.0.beta) lib/rack/showexceptions.rb:24:in `call'
  rack (1.6.0.beta) lib/rack/commonlogger.rb:33:in`call'
  rack (1.6.0.beta) lib/rack/chunked.rb:54:in `call'
  rack (1.6.0.beta) lib/rack/content_length.rb:15:in`call'
  rack (1.6.0.beta) lib/rack/handler/webrick.rb:89:in `service'
  /home/mateusz/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in`service'
  /home/mateusz/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /home/mateusz/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in`block in start_thread'

  Rendered /home/mateusz/.rvm/gems/ruby-2.1.2/gems/web-console-2.0.0.beta4/lib/action_dispatch/templates/rescues/_source.erb (5.9ms)
  Rendered /home/mateusz/.rvm/gems/ruby-2.1.2/gems/web-console-2.0.0.beta4/lib/action_dispatch/templates/rescues/_trace.html.erb (2.4ms)
  Rendered /home/mateusz/.rvm/gems/ruby-2.1.2/gems/web-console-2.0.0.beta4/lib/action_dispatch/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /home/mateusz/.rvm/gems/ruby-2.1.2/gems/web-console-2.0.0.beta4/lib/action_dispatch/templates/rescues/_web_console.html.erb (0.8ms)
  Rendered /home/mateusz/.rvm/gems/ruby-2.1.2/gems/web-console-2.0.0.beta4/lib/action_dispatch/templates/rescues/diagnostics.html.erb within rescues/layout (21.7ms)
127.0.0.1 - - [06/Nov/2014:17:09:55 +0100] "GET /posts HTTP/1.1" 500 135740 0.3265

**Comment by imkarthikk** [comment]
I'm facing the exact same issue in my Rails 4.2.3 app. I tried reinstalling Rails and all the gems, but it still throws the exact same error. Anything I could do to fix it?
