### ISSUE TITLE
ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key

### ISSUE THREAD

**Issue by cdesch** [CultivateLabs/storytime#51]
When running the rake `rake db:migrate` command to install from the storytime install migrations:

```
 rake storytime:install:migrations
 rake db:migrate
```

I get an AWS error:

```
 rake aborted!
 ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
```

I have both of these keys setup in my `secrets.yml`. Why is there error being thrown?

**Comment by hugoh59** [comment]
Why?
